### PR TITLE
Port to 21w20a. Fixes #109

### LINKED ISSUE #109: [21w19a] Cannot move stacks with the mouse cursor.
**Describe the bug**
When interacting with an inventory, you are unable to click and pick up stacks in the inventory. Shift clicking and tooltips still work fine.

**To Reproduce**
1. Create a block entity with an inventory
2. Create a gui to access this inventory alongside the player inventory.
3. Open the gui and click on any of the stacks, you cannot pick them up.

**Versions:**
 - Mod: 4.0.0-alpha.1+21w11a
 - Fabric API: 0.34.4+1.17
 - Minecraft: 21w19a

### PR DESCRIPTION
**Pull request by Rover656**
This ports LibGui to 21w20a, bumping to Java 16 and fixing #109.

### CODE REVIEW

File: src/main/java/io/github/cottonmc/cotton/gui/SyncedGuiDescription.java [hunk 1]
```diff
@@ -148,18 +148,20 @@ public void onSlotClick(int slotNumber, int button, SlotActionType action, Playe
...
 				} else {
 					slot.markDirty();
 				}
 			}
-			
+
+		} else {
+
 			super.onSlotClick(slotNumber, button, action, player);
 		}
```
Comment (Juuxel) [inline src/main/java/io/github/cottonmc/cotton/gui/SyncedGuiDescription.java:162]: Instead of adding the `else`, you should just move the `super.onSlotClick` call to be after the if block (I think this is actually my fault from the initial 1.17 port)

**Review by Juuxel — CHANGES_REQUESTED** [review]
Thanks for the PR! Just a couple of small comments.

Please also revert the indentation changes in `SyncedGuiDescription`, they make the diff a bit hard to read.

File: src/main/java/io/github/cottonmc/cotton/gui/SyncedGuiDescription.java (hunk 1 above)
Comment (Rover656) [reply src/main/java/io/github/cottonmc/cotton/gui/SyncedGuiDescription.java:162]: I added the else as this is what it was in the last 3.x release. I thought this would be correct to re-add because otherwise ScreenHandler#internalOnSlotClick's QUICKMOVE action will also be fired. I'll change this though if you think this is correct :) And indentation changes will be fixed once I receive your answer :)

Comment (Juuxel) [reply src/main/java/io/github/cottonmc/cotton/gui/SyncedGuiDescription.java:162]: Yeah, the else actually seems to be correct - so my fault when porting as I guessed :^)

That should be fine if you also fix the spacing around there (remove the two empty lines around `} else {`).

Comment (Rover656) [reply src/main/java/io/github/cottonmc/cotton/gui/SyncedGuiDescription.java:162]: Sounds good; I shall push these changes now :)

**Review by Juuxel — APPROVED** [review]

**Comment by Juuxel** [comment]
Thanks for the port! I'll release this in a moment.

**Comment by Rover656** [comment]
No problem at all!
